color0 #1c1c28
color1 #c25b5b
color2 #8baa82
color3 #e6c27a
color4 #6270a8
color5 #9a7398
color6 #95b3b0
color7 #f2eadf
color8 #2a2a38
color9 #c25b5b
color10 #8baa82
color11 #e6c27a
color12 #6270a8
color13 #9a7398
color14 #95b3b0
color15 #fff8f2
background #0a0a12
selection_foreground #0a0a12
cursor #e4ded2
cursor_text_color #0a0a12
foreground #e4ded2
selection_background #e4ded2
active_border_color #8b2e2e
inactive_border_color #8baa82

active_tab_foreground   #1c1c28
active_tab_background   #8b2e2e
inactive_tab_foreground #f2eadf
inactive_tab_background #14141e
cursor_trail_color      #f2eadf
